### ISSUE TITLE
Changes to EvB flashlists

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQAggregator#16]
Hi,

as mentioned this morning, EvB version 4.5.0 will bring a couple of changes to the flashlist online. The depreciated parameters have been kept for backwards compatibility, but are no longer filled. Mostly the parameters counting messages since the start of the run have been replaced by corresponding rate parameters. Rates are always in Hertz.

Remi

| component | old | new | type | comment |
| --- | --- | --- | --- | --- |
| RU/EVM | requestCount | requestRate | uint32 | total rate of event request messages from BUs |
|  | fragmentCount | fragmentRate | uint32 | total rate of event fragment messages going to the BUs |
|  | payloadPerBU | throughputPerBU | vector of uint64 | Bytes/s going to each BU |
|  | n/a | buTids | vector of uint32 | List of BU TIDs, order corresponds to other per-BU vectors |
|  | n/a | fragmentRatePerBU | vector of uint32 | rate of event fragment messages for each BU |
|  | n/a | retryRatePerBU | vector of double | rate of retries to send I2O message for each BU |
|  | requestCountPerBU | removed |  |  |
|  | dataReadyCount | removed |  |  |
| EVM | n/a | allocateRate | uint32 | rate of messages going to the RUs |
|  | n/a | allocateRetryRate | double | rate of retries to send messages to the Bus |
| BU | bandwidth | throughput | uint64 | Bytes/s flowing through the BU |
|  | requestCount | requestRate | uint32 | rate of event request messages going to the EVM |
|  | n/a | requestRetryRate | double | rate of retries to send messages to the EVM |
|  | fragmentCount | fragmentRate | uint32 | rate of event fragment messages received from the RUs |
|  | n/a | slowestRUtid | uint32 | the RU TID which delivers the fragments last |

**Comment by m-gl** [comment]
Thank you for detailed change summary. I will inform you when they are introduced in DAQAggregator.

**Comment by ghost** [comment]
Changes introduced to the most recent dev version of the cmsdaq/DAQAggregator.
