### ISSUE TITLE
RU 'isEVM' attribute is renamed to 'evm' when persisting

### ISSUE THREAD

**Issue by Phil2812** [cmsdaq/DAQAggregator#17]
In the JSON snapshot, the RU attribute is called "evm" instead of "isEVM". I suppose this is done by Jackson, as the model's getter is named "isEVM" and of type boolean, just like the Java attribute itself.

From the model point of view, the attribute should be called isEVM in the snapshot as well (unless we change it to just evm in the Java model), yet this would require us to rename the getter to isIsEVM or getIsEVM. Otherwise, adding a Jackson annotation to the RU MixIn might also work (untested):

`@JsonProperty("isEVM")`
`abstract boolean isEVM();`

**Comment by m-gl** [comment]
This is exactly how it should be fixed - annotation in mixin class. We shouldn't touch model field/methods names to fix persistence problems. This annotation is also used for generating "ref_" prefixes in expert API. Could you please commit this change to dev branch? Tommorow morning I will prepare new release of DAQAggregator to deploy in P5 (introducing Michail subfedbuilder fixes)

**Comment by Phil2812** [comment]
I am also in favor of adding the annotations to the mixin, as the alternatives make little sense. Michail is working on the aggregator and the data model right now, so he will be taking care of making this small addition as well.

**Comment by ghost** [comment]
Confirmed. I will add an annotation.
