### ISSUE TITLE
Handle SubFEDBuilders containing only pseudo-FEDs

### ISSUE THREAD

**Issue by Phil2812** [cmsdaq/DAQAggregator#20]
As evident by looking at a non-production DAQ View such as: http://cmsdaqweb.cms/local/daqview/daqdev/DAQ.html there might be SubFEDBuilders containing only pseudo-FEDs.

Obviously, these SubFEDBuilders (rows in the DAQView) do not have a FRLPc, meaning that the current SubFEDBuilder JSON ID generation is unable to handle this case properly.

Besides that, the current mapping creates SubFEDBuilders by looping over the FRLs, which does not create SubFEDBuilders containing only pseudo-FEDs, as these FEDs are not connected to FRLs but to other FEDs instead.

I don't see a way of representing a pseudo-FED-only SubFEDBuilder in the current model, as there is no direct link between the SubFEDBuilder and its FEDs. It is not possible to find them using the FRLs as discussed before and the TTCP linked to the SubFEDBuilder might reference additional FEDs that are not related to the SubFEDBuilder.

These additional SubFEDBuilders might be "invented" by the application processing the snapshots (by processing the dependent FEDs, creating SubFEDBuilders for them if applicable and adding some sort of link between the SubFEDBuilders and their pseudo-FEDs). Although, since the current model is supposed to represent the DAQ View's components, there would be (and currently are) missing SubFEDBuilders in the model.

**Comment by ghost** [comment]
Fixed by addding list of pseudofeds to the subfedbuilders. All missing subfedbuilders are handled in the model side.
