### ISSUE TITLE
Only one FRL per SubFEDBuilder

### ISSUE THREAD

**Issue by Phil2812** [cmsdaq/DAQAggregator#21]
In current snapshots there seems to be only one FRL in each SubFEDBuilder. This bug is most likely caused by these lines:

https://github.com/cmsdaq/DAQAggregator/blob/125c24d4472a2da2c23390bb00897f5f48b90e2a/src/main/java/rcms/utilities/daqaggregator/mappers/MappingManager.java#L136-L140

Line 137 in particular, as the FEDBuilder's hash code is never added to the map's key set, therefore a new Set is created on every iteration, discarding the previously added FRLs.

This:

`if (!subFedBuilderToFrl.containsKey(fb.hashCode())) {`

should probably be:

`if (!subFedBuilderToFrl.containsKey(sfbId)) {`

**Comment by Phil2812** [comment]
Actually, there seems to be another issue in the same method. There is only one FRL added to a SubFEDBuilder for each FRLPc that is found. The code is looping over the FRLs, but only connects the current FRL to the SubFEDBuilder, if the FRL's FRLPc is not yet contained in the ttcPartitionToFrlPCs map. However, multiple different FRLs in the same SubFEDBuilder obviously also have the same FRLPc. Please correct me if I am wrong. I currently don't have a working version of the aggregator running, otherwise I would do some debugging.

**Comment by ghost** [comment]
The first is now fixed, I will also handle the second.

Latest working version is at cmsdaq/DAQAggregator dev branch [Latest commit a639f3e]. It does not include these fixes yet.

**Comment by ghost** [comment]
Fix committed
