### ISSUE TITLE
Inadequate identification of subFEDbuilders

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#22]
By looking at the current DAQView at a yesterday's code review with Philipp, it seems that identifying subFEDbuilders uniquely (both in model object mapping and in persistence) with an id composite of TTCP and FRLPc, is probably not able to cover some cases which exist (quite often) in production. Currently, two subFEDbuilders, under two different FED builders that, nevertheless, are defined by the same pair of TTCPartition and FRLPc, will be mapped to the same subFEDbuilder object of the model.

An example (there are multiple cases) from the current DAQView:
TTCP=TEC+:26 - FRLPc=s1d06-25-01  > Used by two different FEDbuilders, TEC+3a and TEC+3b

Given that FEDbuilder names are unique, they should probably also participate in the composite natural ID of the subFEDbuilders, in order to fully differentiate between different subFEDbuilders.

**Comment by andreh12** [comment]
just to add my two cents: the code in the current daq2view ( rcms/utilities/daqview/JMonHTMLTableFB.java -- look for statements where the variable`rowcount` is incremented) has actually an outermost loop over the fedbuilders:

```
for (Long fbId : orderedFBList) {
  ...
  for (Long fbi_id : new TreeSet<Long>(fb.getFBIs().keySet())) {
    ...
    for (Integer frlIO : frl.getFEDs().keySet() ) {
      ...
    }
  }
  ...
  fbRowCountMap.put(fbId, rowcount);
}
```

The display loop in the same file also has an outer loop over fedbuilders:

```
                for (Long fb_id : orderedFBList) {
                        ...
                        String rowSpan = "";
                        if (fbRowCountMap.get(fb_id)>1)
                                rowSpan = " rowspan=" + fbRowCountMap.get(fb_id);
                   ...
                 }
```

**Comment by ghost** [comment]
Thanks for this pointer to daq2view code. The same pattern is also followed on the DAQAggregator,).
I think the problem lies on relation maps subFEDBuilder to FRL/FRLPc, which lie outside the outermost loop over the FEDbuilders.
As a result, when having processed the FEDbuilder TEC+3a (from my example above) and the loop continues to process the FEDbuilder TEC+3b, it does not add a new sufFEDBuilder but, rather, overwrites information on the one existing from TEC+3a (e.g. adds an FRL found under this new FEDbuilder). At the end, a single subfedbuilder will conceptually belong to two different FEDbuilders. Of course, its back-reference points to TEC+3a, but it is pointed by both TEC+3a and TEC+3b.
