### ISSUE TITLE
Missing field in flashlist definition?

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#27]
While probably not a purely DAQAggregator issue, this was discovered in its context, so it is probably interesting to record here, for reference.

At the usage of flashlist  types FMM_PARTITION_DEAD_TIME, FMM_FED_DEAD_TIME it is mentioned that these should be downloaded in a session context. This is implemented by using a sessionId GET parameter when downloading, whose value is matched against a corresponding column in LAS (usually labeled "sessionid" or "SID").
However, the two flashlists mentioned above, do not seem to contain any colum relevant to the session id. This has not been exposed yet, as neither of these flashlists is actuallly downloaded in the current development configuration of the aggregator. But if they are actually downloaded with session context enabled, they will contain zero tuples.

Do these flashlists are actually supposed to be downloaded in a session context? If so, is there a column missing at LAS?

**Comment by hsakulin** [comment]
FMM_PARTITION_DEAD_TIME, FMM_FED_DEAD_TIME are only meant for storing dead times to DB through XMAS Store. They are not used in online monitoring.
