### ISSUE TITLE
Sleep time in case of error

### ISSUE THREAD

**Issue by m-gl** [cmsdaq/DAQAggregator#28]
Sometimes there is error in main loop e.g.No active session found for toppro and PublicGlobal

If the error lasts for few hours there will be a lot of stack traces in logs. We could have dynamic period of sleeping if error occurs. Start with 2s then increase it each time the error repeats until it reaches some limit e.g. 5 minutes.

**Comment by hsakulin** [comment]
In principle a good idea, but 5 minutes is way too long. I would go to 30 seconds at most.

**Comment by Phil2812** [comment]
In the mentioned case that no active session is found, I would not reduce the sleep time to something that high. Maybe do some exponential backoff up to around half a minute, although I think the better option would be not to print the stack trace in case there is no session. This is not really an unexpected error and knowing that there is no session would probably be enough and can be communicated by logging a single line. It can be an Error or Warning, but it's not like the Stacktrace provides any benefits in this particular case. Generally, we should try to handle expectable exceptions properly. And it is not particularly uncommon that there is no session for an extended period of time.

**Comment by m-gl** [comment]
Enumeration of known errors introduced in release 1.4.0 [DAQExceptionCode](https://github.com/cmsdaq/DAQAggregator/blob/master/src/main/java/rcms/utilities/daqaggregator/DAQExceptionCode.java). We will NOT print stacktrace for known exceptions in main loop.
