### ISSUE TITLE
Natural ids: unnecessary id field

### ISSUE THREAD

**Issue by m-gl** [cmsdaq/DAQAggregator#29]
I'm switching to use mixins from DAQAggregator in DAQExpert API. Current natural ids are stored in '@id' field but 'id' field is also generated. You can see it below.

I understand that @id is generated by id generator you have implemented, and 'id' fields are unnecessary. You are not using that field whatsoever. 

**Please confirm that.** 

I will then remove the fields id from all classes, e.g.:
`private final String id = "busummary";`

```
{
  "@id": "DAQ",
  "sessionId": 283305,
  "runNumber": 279019,
  "lhcMachineMode": "PROTON PHYSICS",
  "lhcBeamMode": "INJECTION PHYSICS BEAM",
  "daqState": "Running",
  "levelZeroState": "Running",
  "dpsetPath": "/daq2/eq_160715/fb_all/dp_bl329_75BU",
  "lastUpdate": 1471535815270,
  "buSummary": {
    "@id": "BUS",
    "id": "busummary",

(..)
  "id": "daq"
}
```

**Comment by ghost** [comment]
This field exists in type definitions as far as I can see and is not generated by the mixins. Probably leftover from earlier id implementation.
In the cases of DAQ, BUSummary and also FEDBuilderSummary I can confirm that it is useless and it's the case above.
In other cases, such as FRL, FMM and FED, the 'id' field has valid meaning as a value from the hw db.
