### ISSUE TITLE
Extra FEDs that should not make it into the model

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#36]
The two (pseudo)FEDs with srcId 103 and 388 make their way into the Aggregator's model, while they are not actually part of the configuration. The reason is that hardware feds are populated over the equipment set without any checks or exceptions. The Java DAQView provides an alternative way to get the hardware feds that should actually make their way into the model (indeed, these two feds are not included in the current daqview, but they are included when visualising the model using the new daqview application).

**Comment by ghost** [comment]
Fixed by changing the FED set retrieval to go through the DAQ partition RUs and taking into account the FRLInputEnableMask at each FBI.

However, at the relation mapping stage where links between hardware objects are retrieved, the full sets of the equipment sets are still used; and these still contain the two extra feds. For example, links between frls and feds are retrieved by calling hwfrl.getFEDs() over each FRL in the eq set. As these refer to FEDs missing from the object collection (103 and 388), null pointer exceptions are thrown.
The simplest way to solve this was to add checks at links retrieval between feds and other objects (namely in functions mapRelationsFmmToFed, mapRelationsFrlToFed, mapRelationsTTCPToFed of the RelationMapper) and make sure that a relation will only be created if the FED part refers to a FED that has actually been included in the model. If you feel this check is not enough or that should be extended to other parts of the relation mapping, let me know.

I would also like to point out that in the current DAQView, TTC partitions also seem to be retrieved through the DAQ partition RUs, in the same loop as FEDs. In the DAQAggregator they used to be retrieved through the FEDs as far as I can see from some old commented out code, but right now they are being retrieved directly from the equipment set. Since the FED retrieval is now fixed, maybe it would make sense to revert to the old way.

**Comment by hsakulin** [comment]
Please go from RU to Fedbuilder to FRL to FED (the latter taking into account the FBI mask), everywhere.

**Comment by ghost** [comment]
On it now. As we will also need to update retrieval for other data types (subsystems, frlpcs) and changes will be required at RelationMapper and MappingManager (where the subfedbuilders are being created), I will report in a ticket once the modifications are there.

**Comment by ghost** [comment]
Fully handled in merge #40. Some details:

Object mapping changes:

-FEDs are now retrieved through the Ru.Fb.Frl chain (for each RU), taking into account the fb's FRLInputEnableMask in deciding whether to include a FED or not.

-FRLs are included similarly as above (as they are FEDs' parents in the aforementioned chain)

-TTCPs are retrieved over the FEDs (with FED collection defined as above) and Subsystems are retrieved over TTCPs, instead of directly using the equipment set. This resulted in much fewer TTCPs being included, but all TTCPs that appear in the production DAQView were still included*. 

-SubFEDBuilders creation now takes into account the FRLInputEnableMask, to be consistent with the FED retrieval. If a FED would not be retrieved at first place, then neither the SubFEDBuilder creation loop would create a new SubFEDBuilder out of this FED's TTCP and FRL/FRLPC.

Relation mapping changes:
Wherever objects of the types mentioned above are looped over, there was an update of retrieval loops in accordance with the new retrieval code at object mapping. Namely:

-FmmToFed (since an FMM may refer to multiple FEDs and since not all of the equipment set's FEDs are now in the model, check was introduced to avoid linking an FMM to an unknown FED)

-FmmToTTCP (now getting TTCPs through RUs, through FBs, through FRLs, through FEDs)

-FrlToFed (link creation takes into account the FRLInputEnableMask)

-SubsystemToTTCP (TTCPs are retrieved through FEDs and each refers to a Subsystem, for which a link is restored. This is a replacement of going through Subsystems and linking to all their TTCPs, assuming all are in the configuration. Judging from the reduced number of TTCPs (mentioned above), this is not true for a number of Subsystems*).

-TTCPToFed (links restored by a loop over FEDs and their respective TTCPs, instead of a loop over the equipment set TTCPs)

*(whether this is expected, should be confirmed)

If there is nothing to add, this can be closed.

Michail
