### ISSUE TITLE
DAQAggregator for all setups

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#52]
There should be the possibility of running parallel Aggregators to produce snapshots for all daq setups upon request, not only cdaq. This would allow (among other benefits) the new DAQView to achieve the information completeness of the old one, for all use cases. Things to take into account:

1) Persistence of snapshots (allocate new storage area-directory for each supported setup)

2) Accessing the different configurations (that is: creating different configuration files and start parallel aggregators with them)

3) Serving of snapshots. We could use a single API (with an extra parameter for setup).This API could be a standalone app and should be notified whenever a new setup is added (e.g. with a properties file that is checked every some seconds and contains entries of the type: setup_name->storage_path).

4) Eliminate hardcoded bits of the DAQAggregator that are specific to cdaq. I report the following:

- At FlashlistDispatcher, we use the harcoded service name "cpm-pri" and the hardcoded type names "tts_ici" and "tts_apve". These are used to extract the correct rows from the TCDS_PM_TTS_CHANNEL flashlist and at the time of hardcoding them, there was apparently no way (or need) to dynamically know these information.

- For the TTS P and A state hyperlinks at the DAQView, we use a hardcoded host:port. This is, of course, a (DAQ) View problem but it should be solved at model level, because it is function of the setup, as well.

**Comment by ghost** [comment]
Adding to point 4: hardcoded cdaq info
RelationMapper.getTopFMMForPartition contains hardcoded TTCP names "CPM-PRI" and "CPM-SEC" and hardcoded trigger name "TCDS-PRI"

**Comment by hsakulin** [comment]
1) ad CPM-PRI and CPM-SEC: this list should be extended to any partition starting with CPM, LPM, DVCPM, DVLPM (with case ignored).

2) Getting the trigger name:

from the new tcdsFM flashList you will get the pmURL, pmLID and pmService

Using pmURL and pmService you need to loop over all PMs in all triggers. If you find a match of a PM to the pmURL and pmService, you know what trigger you are using.

If there is no TCDSFM flash list available, try to find a Trigger with name GTPe. But in this case we need some special treatment to find the top level FMM as the GTPe has no PMs and iCIs and PIs. In this case the FMMTriggerLinks go directly from the top level FMM to the trigger. lpmNr and iciNr are -1, triggerIO gives the IO on the GTPe.

If you can work on getting the pmURL and pmService into this method, I can help with the rest of the code.

**Comment by ghost** [comment]
Implemented, without the special treatment when the GTPe trigger is selected due to lacking TCDSFM flashlist information.
You can review the code here: https://github.com/mvougiou/DAQAggregator/blob/dev/src/main/java/rcms/utilities/daqaggregator/mappers/RelationMapper.java#L384

If this is correct, we can proceed to the special case.
