### ISSUE TITLE
Application homepage port for frlpcs,rus,bus

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#54]
DAQView needs to know the hostname (which it does know), as well as the port that the frlpc,ru and bu applications run, so that the hyperlinks become functional and point to the XDAQ homepage of each host.
While in cdaq that port was 11100 for all hosts, in daqval it seems to be 11600.
This information should dynamically be available for the DAQView, therefore I suggest adding it to the model. If you agree, I would take it from the "context" flashlist variable.

**Comment by m-gl** [comment]
Where do you want to add this information to the model?

**Comment by ghost** [comment]
Conceptually they are part of each frlpc,ru,bu host, but if the port can be guaranteed to be the same across one setup, then 3 variables (or even 1, if port is the same for all three types of host across one setup) would suffice and I would put them directly under the DAQ object, or in a "metadata" child of DAQ.

**Comment by hsakulin** [comment]
The ports are not guaranteed to be fixed across the setup. They have to be stored with each host. We can for example run multiple frlcontrollers on a machine which would then run on different ports.

And yes, you need to take the port from the context, just as done in daqview.
