### ISSUE TITLE
When to reload the structure from hardware database?

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#55]
To give an answer to the discussion we had yesterday, concerning whether the structure is reloaded at each new session and whether this is correct, I took a look and it seems that the structure is actually reloaded and is used to rebuild DAQ model each time a new session is detected OR a new hwcfg_key is detected. Hence it looks like the structure is rebuilt more often than needed, rather than less often.
For reference, see method detectNewSession() at [SessionDetector](https://github.com/cmsdaq/DAQAggregator/blob/dev/src/main/java/rcms/utilities/daqaggregator/datasource/SessionDetector.java) class, where the relevant flag is set. Of course the naming can be changed to something more intuitive.

**Comment by m-gl** [comment]
Yes, both session change or hwcfg_key change trigger the rebuild. Sorry for confusion yesterday - I forgot how I implemented this. The test covering cases when it's rebuilt is here: [SessionDetectorTest](https://github.com/cmsdaq/DAQAggregator/blob/master/src/test/java/rcms/utilities/daqaggregator/datasource/SessionDetectorTest.java)
