### ISSUE TITLE
failing to build with maven

### ISSUE THREAD

**Issue by andreh7** [cmsdaq/DAQAggregator#6]
when checking out the current head (b688861ff3a342e70f23cf04719b164f872687d1) and building it with

```
   mvn install
```

I get the following error:

```
Project ID: com.google.code.gson:gson-parent

Reason: Invalid JDK version in profile 'doclint-java8-disable': Unbounded range: [1.8, for project com.google.code.gson:gson-parent
```

Searching a bit, it looks like I'm affected by issue 819 in https://github.com/google/gson . Changing the gson version from 2.6.2 to 2.6.1 in pom.xml makes the problem go away for me.

Unless we really need 2.6.2, I'd suggest to move back to 2.6.1 . I can prepare a pull request if needed.

**Comment by m-gl** [comment]
We don't need gson. It's useless in our case because it cannot persist graph with circular dependencies. It's in dependecies because I tested it few weeks ago choosing the right serializer and forgot to remove. I will remove it.
