### ISSUE TITLE
FRL Masking at Ferol40

### ISSUE THREAD

**Issue by ghost** [cmsdaq/DAQAggregator#60]
Hi,

In the current use of system by HCAL partitions, I see that a number of FEROL40 FEDs are being used (based on the convention of srcID over 1024).

However, I do not see any FEROL40 flashlists in the LAS for cdaq. Among others, this leads to missing FRL masks at these FEDs, as I had been asked to include FRL masking from the new FEROL40 flashlists, not from the Level 0 static flashlist, as done with legacy FEDs.

At this moment, the masking information already exists in the Level 0 static flashlist for both legacy and new FEDs (again, based on the srcID>1024 convention).

Is there still a reason not to include the masks from there?

Cheers,
Michail

**Comment by mommsen** [comment]
Hi Michail,

you're confusing 2 things:  srcID>1024 denotes uTCA FEDs (in contrast to the legacy VME FEDs.) But both can be read out by the FEROL. There is no FEROL40 in production, yet.

Cheers,
Remi

**Comment by ghost** [comment]
Hi Remi,

OK, thank you for making this clear. I got the convention wrong.

So, the masking info of FEDs that will eventually be read out by FEROL40 won't be possible to be taken from the FED_ENABLE_MASK of L0 static?

Cheers,
Michail
