### ISSUE TITLE
RU fedIdsWithoutFragments should only be considered when rate is 0

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQAggregator#71]
Hi,

I noticed in the react DAQView, that the RU displays spurious FED IDs which have not sent any data. This FED IDs are listed in "fedIdsWithoutFragments" in the RU/EVM flashlist. Checking in the old DAQView code, this field is only displayed if the RU is stuck:

`if ( fields.containsKey("fedIdsWithoutFragments") &&
	Integer.parseInt( fields.get("eventRate") ) == 0 &&
	Integer.parseInt( fields.get("incompleteSuperFragmentCount") ) > 0 )`

I guess this should go into the aggregator, too.

Cheers,
Remi

**Comment by ghost** [comment]
Implemented in DAQView and will soon be deployed.

**Comment by mommsen** [comment]
This condition is now implemented on the RU/EVM. Thus, it could be removed from the DAQView code, again.

Remi
