### ISSUE TITLE
DAQ state in Error when BU is Blocked

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQAggregator#80]
Hi,

while debugging the new EvB version in daqval, I noticed that the DAQ state is reported in Error when a BU is in blocked state:
http://daq-expert.cms/daq2view-react/index.html?setup=daqvaldev&time=2017-05-16-11:19:51

The EvB is running fine at 200 Hz and the DAQ FM is in Running state. Once I unblocked the BU, the DAQ state went back to Running:
http://daq-expert.cms/daq2view-react/index.html?setup=daqvaldev&time=2017-05-16-11:28:46

Remi

**Comment by m-gl** [comment]
The DAQ state is retrieved from flashlist `LEVEL_ZERO_FM_SUBSYS`, column `STATE` from the row where `SUBSYS` column equals `DAQ` and `FMURL` column contains filter strings:

For daqvaldev:
- cmsrc-daqval
- 31500

For daqvalpro:
- cmsrc-daqval
- 11500

Unless this is incorrect approach the value was wrong in the flashlist.

**Comment by mommsen** [comment]
I tried to reproduce it in daq2val today, but failed. I guess this was some kind of glitch somewhere.
