### ISSUE TITLE
add FED type to snapshot

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQAggregator#83]
distinguish the following types: 

- SLINK
- SLINKExpress6G
- SLINKExpress10G
- FEROL40_10G
- FEROL40_6G

**Comment by m-gl** [comment]
Implemented in branch feature/mtca-feds. Will be released with uTCA FEDs, see #85

**Comment by m-gl** [comment]
Released as 1.13.0 and deployed to production Tue Jun 13.
