### ISSUE TITLE
filter all flashlists by DAQ session id

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQAggregator#84]
all flashlists (not only `LEVEL_ZERO_FM_SUBSYS` as discussed in #44) should be filtered by the session id taken from the DAQ subsystem.

Filtering on the LAS with a URL parameter is no longer supported, so the DAQAggregator needs to filter in its own code.

**Comment by m-gl** [comment]
Implemented, released in 1.10.0.
