### ISSUE TITLE
support for TCDS_CPM_RATES_1HZ flashlists

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQAggregator#94]
`TCDSGlobalInfo` should also support reading values from the `TCDS_CPM_RATES_1HZ` in addition to `TCDS_CPM_RATES` which it already reads.

As @gladky mentioend, adding values for `TCDS_CPM_DEADTIMES_1HZ` (while keeping `TCDS_CPM_DEADTIMES`) was straightforward because content taken from `TCDS_CPM_DEADTIMES` was grouped in the field `deadTimes` of class `TCDSGlobalInfo`. Adding the `_1HZ` flashlist translated into adding another field `deadTimesInstant`. 

However, the information obtained from `TCDS_CPM_RATES` is spread across several fields in class `TCDSGlobalInfo`.

Several possible solutions are:

1. duplicate the existing fields (`trg_rate_total` etc.) and add a prefix/suffix `instant`. Pro: schema stays backwards compatible, Con: not very elegant
1. group the existing fields into a new class and have two fields, one for the 'classic' rates updated every lumi section and one for the instantaneous ones. Pro: preferred solution, Con: a priori breaks the possibility to read the snapshot archives (DAQExpert browser and DAQView).

We should check if we can do schema evolution in `Jackson` (the framework used for serializing the `DAQ` snapshot objects) supports.

**Comment by andreh12** [comment]
[This link](http://www.baeldung.com/jackson-deserialization) contains an example of a custom deserializer for Jackson. From the example it looks like such custom serializers can be registered on a per class basis (`TCDSGlobalInfo` in our case). 

We could write a custom serializer for the current class structure when moving to a new structure.

**Comment by m-gl** [comment]
Useful link. We could fix the problem with one custom deserialiser able to handle old and new versions of the class. The problem is once we introduce such custom deserialiser we have to update it even if we simply add a new field to the class. If I understood correctly once we switch to custom we have to handle everything ourselves. I could not find the way to fire custom serialiser (for old version of the object) only if standard one fails. This would be the case in this situation.

What may be worth checking out is this: https://github.com/galan/verjson
The project seems not very mature, I couldn't find Jackson alternative.

**Comment by andreh12** [comment]
I also saw the verjson but we should first find out how much effort is behind this project.

**Comment by andreh12** [comment]
A potential solution based on [this](https://stackoverflow.com/a/39314217/288875), [this](https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations#mix-ins-to-the-rescue) and [this](https://github.com/FasterXML/jackson-annotations#changing-property-auto-detection) looks as follows:

* factor out a class `TCDSTriggerRates` from `TCDSGlobalInfo` containing the relevant fields, adding a field `triggerRates` of type `TCDSTriggerRates` to class `TCDSGlobalInfo`
* leave the getters and setters in `TCDSGlobalInfo` as is, delegating to the field `triggerRates`
* add the following mixin somewhere:
```
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, 
  getterVisibility = JsonAutoDetect.Visibility.PUBLIC_ONLY, 
  setterVisibility = JsonAutoDetect.Visibility.PUBLIC_ONLY)
	abstract class TCDSGlobalInfoMixin {
	}
``` 
This forces Jackson to use only public getters and setters without looking at the actual fields.
* in `StructureSerializer.deserialize()` add the following after obtaining the mapper object:
```
mapper.addMixIn(TCDSGlobalInfo.class, TCDSGlobalInfoMixin.class);
```

I tried this, its possible to read the old structure files (because of the modification in `StructureSerializer.deserialize()` and writes out new format files because StructureSerializer.serialize()` remains unchanged (i.e. it writes out a `.json` file with a `triggerRates` sub-object as a member of `tcdsGlobalInfo`).

I can push the code to a demo branch so that you can have a look.

**Comment by m-gl** [comment]
Yes, please do push. Does it read the new files as well?

**Comment by m-gl** [comment]
I pushed a demo with verjson solution here https://github.com/cmsdaq/DAQAggregator/commit/3720efa9faa2a0e0a87a1ad7a4819ada11c506d3

I reproduced our situation in micro scale using 2 json files:

```
{
  "$v": 1,
  "$d": {
    "other": "other value",
    "number": 1,
    "text": "value"
  }
}
```

```

{
  "$v": 2,
  "$d": {
    "wrapper": {
      "text": "value",
      "number": 1
    },
    "other": "other value"
  }
}
```

What is annoying about this solution is the fact that it expects meta information inside files - a version number. Of course it makes sense but we want to avoid modifying the past snapshots. We could simply consider all past snapshots to be of version 1 without modifying the files and use this versioning from now on.

**Comment by andreh12** [comment]
I will push demonstrator later (for the record).

For the moment we (@hsakulin, @gladky and me) decided to go with the semi-elegant solution and just adding the instantaneous values in a new class (for reasons of time pressure). We can revisit this later.

**Comment by andreh12** [comment]
The semi-elegant solution is being put together in pull request #96 .

**Comment by andreh12** [comment]
I guess we can close this issue since #96 has been merged ?
